language: go
before_install: ["go mod download"]
script: script/test
sudo: false
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - GO111MODULE=on
go:
  - "1.11"
matrix:
  fast_finish: true
notifications:
  email:
    recipients:
      - jordon@envygeeks.io
    on_success: change
    on_failure: change
branches:
  only:
    - master
